### ISSUE TITLE
Question about Munk spelling fix

### ISSUE THREAD

**Issue by mikemc** [naobservatory/mgs-pipeline#2]
In https://github.com/naobservatory/mgs-pipeline/commit/03edb6bfc771408466c3cf43acd82919663317f9 it seems like there was a rename operation that didn't actually fix the spelling in the filename of https://github.com/naobservatory/mgs-pipeline/blob/main/papers/Munk2022/monk-2022-supplementary-data-1.tsv; was that intentional?

**Comment by jeffkaufman** [comment]
Thanks for catching that one; fixed in 6b1fe9b
